# Generated by Django 4.0.5 on 2022-06-09 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('approach', models.CharField(max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=5)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('continent', models.CharField(blank=True, max_length=20)),
                ('elevation', models.CharField(blank=True, max_length=10)),
                ('google_maps_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClimbEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('attendees', models.ManyToManyField(blank=True, to='posts.climbuser')),
                ('mountain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.mountain')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='climb_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
