# Generated by Django 4.0.5 on 2022-06-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_date_climb_climb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='climb_date',
            field=models.DateField(verbose_name='%m/%d/Y'),
        ),
    ]
