# Generated by Django 4.0.5 on 2022-06-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_climb_climb_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountain', models.CharField(max_length=50)),
                ('climb_date', models.DateField()),
                ('completed', models.BooleanField(default=False, verbose_name='summited')),
            ],
        ),
        migrations.DeleteModel(
            name='Climb',
        ),
    ]
