# Generated by Django 4.0.5 on 2022-06-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_climbevent_attendees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClimbUser',
        ),
    ]
