# Generated by Django 4.0.5 on 2022-06-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_delete_climbuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountain',
            name='glaciated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='route',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
