# Generated by Django 4.0.5 on 2022-06-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_climbevent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbevent',
            name='climb_date',
            field=models.DateField(null=True),
        ),
    ]
