# Generated by Django 4.0.5 on 2022-06-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_mountain_glaciated_alter_mountain_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
