# Generated by Django 4.0.5 on 2022-06-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_mountain_country_alter_mountain_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbevent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
